services:
  backend:
    image: backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - ./backend:/app/backend
    depends_on:
      - db
    ports:
      - 4200:4200
    command:
      [
        "flask",
        "--app",
        "startup:app",
        "run",
        "--host=0.0.0.0",
        "--port=4200",
        "--debug",
      ]

  frontend:
    build: ./frontend
    container_name: frontend_c
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules

  db:
    image: postgres:17-alpine
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  adminer:
    image: adminer
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8080:8080

  # This service is used to run the init script
  # Usage: docker compose run init
  init:
    image: python:3-slim
    volumes:
      - .:/app
    profiles:
      - init
    command: ["python", "/app/scripts/init.py"]

  # docker compose run test-backend
  # Run backend tests and exit
  test-backend:
    image: backend
    profiles:
      - manual
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - ./backend:/app/backend
    command: bash -c "pytest /app/backend"

  # docker compose run test-backend-watch
  # Run backend tests and watch for changes
  test-backend-watch:
    image: backend
    profiles:
      - manual
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - ./backend:/app/backend
    command: bash -c "ptw /app/backend"