version: '3.4'

services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5002:5000
  
  frontend:
    build: ../frontend
    container_name: frontend_c
    ports:
      - '3000:8080'
