"""make group number necessary

Revision ID: 09b36a3b8536
Revises: 9e9c52518be2
Create Date: 2025-03-14 13:33:28.682027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09b36a3b8536'
down_revision: Union[str, None] = '9e9c52518be2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('group', 'group_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('group', 'group_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
