"""update foreign key constraints

Revision ID: 109a6fb8790f
Revises: 68684692b315
Create Date: 2024-12-16 07:25:51.508097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '109a6fb8790f'
down_revision: Union[str, None] = '68684692b315'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'daily_order', ['person_id'])
    op.drop_constraint('daily_order_person_id_fkey', 'daily_order', type_='foreignkey')
    op.create_foreign_key(None, 'daily_order', 'person', ['person_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('employee_group_id_fkey', 'employee', type_='foreignkey')
    op.create_foreign_key(None, 'employee', 'group', ['group_id'], ['id'], ondelete='CASCADE')
    op.alter_column('old_order', 'person_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('old_order_person_id_fkey', 'old_order', type_='foreignkey')
    op.create_foreign_key(None, 'old_order', 'person', ['person_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('pre_order_person_id_fkey', 'pre_order', type_='foreignkey')
    op.create_foreign_key(None, 'pre_order', 'person', ['person_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pre_order', type_='foreignkey')
    op.create_foreign_key('pre_order_person_id_fkey', 'pre_order', 'person', ['person_id'], ['id'])
    op.drop_constraint(None, 'old_order', type_='foreignkey')
    op.create_foreign_key('old_order_person_id_fkey', 'old_order', 'person', ['person_id'], ['id'])
    op.alter_column('old_order', 'person_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.create_foreign_key('employee_group_id_fkey', 'employee', 'group', ['group_id'], ['id'])
    op.drop_constraint(None, 'daily_order', type_='foreignkey')
    op.create_foreign_key('daily_order_person_id_fkey', 'daily_order', 'person', ['person_id'], ['id'])
    op.drop_constraint(None, 'daily_order', type_='unique')
    # ### end Alembic commands ###
