"""add dish price

Revision ID: 74da865448a0
Revises: f0881fc0bca6
Create Date: 2025-01-29 15:37:23.740531

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "74da865448a0"
down_revision: Union[str, None] = "f0881fc0bca6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dish_price",
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("main_dish_price", sa.Float(), nullable=False),
        sa.Column("salad_price", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("date"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dish_price")
    # ### end Alembic commands ###
