"""add 'date' to daily_orders

Revision ID: 8623f646b5fd
Revises: 109a6fb8790f
Create Date: 2024-12-16 18:18:50.294409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8623f646b5fd'
down_revision: Union[str, None] = '109a6fb8790f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_order', sa.Column('date', sa.DateTime(), nullable=False))
    op.alter_column('daily_order', 'handed_out',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('daily_order', 'handed_out',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('daily_order', 'date')
    # ### end Alembic commands ###
