"""user_id_groupleader user_id_group_leader

Revision ID: aa0dd6eb0e8c
Revises: 51e61ec75dcf
Create Date: 2024-12-06 12:30:57.762247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa0dd6eb0e8c'
down_revision: Union[str, None] = '51e61ec75dcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('user_id_group_leader', sa.UUID(), nullable=False))
    op.drop_constraint('group_user_id_groupleader_fkey', 'group', type_='foreignkey')
    op.create_foreign_key(None, 'group', 'user', ['user_id_group_leader'], ['id'])
    op.drop_column('group', 'user_id_groupleader')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('user_id_groupleader', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'group', type_='foreignkey')
    op.create_foreign_key('group_user_id_groupleader_fkey', 'group', 'user', ['user_id_groupleader'], ['id'])
    op.drop_column('group', 'user_id_group_leader')
    # ### end Alembic commands ###
