"""This script creates the .env file for DEV environment with random values for the secret keys.

Run this script with one of the following commands: 

```
docker compose run init

python scripts/init.py

python3 scripts/init.py
```
"""

from os import path
import string
import secrets

template = path.join(path.dirname(__file__), "..", ".env.example")
output = path.join(path.dirname(__file__), "..", ".env")

if not path.isfile(template):
    print("The template file does not exist.")
    exit(1)

alphabet = string.ascii_letters + string.digits + "#$%&*?@_"

flask_env = "development"
initial_admin_username = "admin"
initial_admin_password = "password"
db_user = "postgres"
db_database = "postgres"
db_host = "db"
db_port = "5432"
db_password = "miau"

jwt_secret = "".join(secrets.choice(alphabet) for _ in range(256))

with open(template, "r") as f:
    lines = f.read()

lines = f"# This file was generated by {__file__}\n\n" + lines
lines = lines.replace("$$FLASK_ENV$$", flask_env)
lines = lines.replace("$$INITIAL_ADMIN_USERNAME$$", initial_admin_username)
lines = lines.replace("$$INITIAL_ADMIN_PASSWORD$$", initial_admin_password)
lines = lines.replace("$$DB_USER$$", db_user)
lines = lines.replace("$$DB_DATABASE$$", db_database)
lines = lines.replace("$$DB_HOST$$", db_host)
lines = lines.replace("$$DB_PORT$$", db_port)
lines = lines.replace("$$DB_PASSWORD$$", f'"{db_password}"')
lines = lines.replace("$$JWT_SECRET$$", f'"{jwt_secret}"')

with open(output, "w") as f:
    f.write(lines)

print(f"File created: {output}")
