"""This script creates the .env file with random values for the secret keys.

The script is supposed to be executed by running: 

```
docker compose run init
```
"""

from os import path
import string
import secrets

template = path.join(path.dirname(__file__), "..", ".env.example")
outputRoot = path.join(path.dirname(__file__), "..", ".env")
outputBackend = path.join(path.dirname(__file__), "..", "backend", ".env")

if not path.isfile(template):
    print("The template file does not exist.")
    exit(1)

alphabet = string.ascii_letters + string.digits + "#$%&*?@_"

flask_env = "development"
db_user = "postgres"
db_database = "postgres"
db_host = "db"
db_port = "5432"
db_password = "miau"

# db_password = "".join(secrets.choice(alphabet) for i in range(256))

with open(template, "r") as f:
    lines = f.read()

lines = f"# This file was generated by {__file__}\n" + lines
lines = lines.replace("$$FLASK_ENV$$", flask_env)
lines = lines.replace("$$DB_USER$$", db_user)
lines = lines.replace("$$DB_DATABASE$$", db_database)
lines = lines.replace("$$DB_HOST$$", db_host)
lines = lines.replace("$$DB_PORT$$", db_port)
lines = lines.replace("$$DB_PASSWORD$$", f'"{db_password}"')

with open(outputRoot, "w") as f:
    f.write(lines)

with open(outputBackend, "w") as f:
    f.write(lines)

print(f"Files created: {outputRoot}, {outputBackend}")
