# Configure Grafana to be available outside
# the cluster on port 30443
grafana:
  service:
    type: NodePort
    nodePort: 30443

kubeProxy:
  enabled: false

# Configure Prometheus to scrape the backend service
prometheus:
  prometheusSpec:
    volumeClaimTemplate:
      spec:
        storageClassName: gluster
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
      selector: {}

    additionalScrapeConfigs:
      - job_name: backend-api
        metrics_path: /api/metrics
        static_configs:
          - targets: ["backend-service.default.svc.cluster.local:4200"]
